### ISSUE TITLE
Error parsing human URDF

### ISSUE THREAD

**Issue by evelyd** [ami-iit/rod#49]
I have been using Mujoco to visualize the robot model, and now I would like to do the same for the human model (I want to use this one: https://github.com/robotology/human-gazebo/tree/master/humanSubjectWithMeshes). I've been using jaxsim as a helper for this, but with the human model I get the following error when I call jaxsim's `build_from_model_description` on the human URDF:
```
Error Code 1: Msg: Error parsing XML in file [/tmp/tmpbdv_is_d/tmpup45_c3y.xml]: Error=XML_ERROR_PARSING_TEXT ErrorID=8 (0x8) Line number=1
Error: SDF parsing the xml failed.

Traceback (most recent call last):
  File "/home/evelyd/miniforge3/envs/baf/lib/python3.11/site-packages/rod/utils/gazebo.py", line 106, in process_model_description_with_sdformat
    cp = subprocess.run(
         ^^^^^^^^^^^^^^^
  File "/home/evelyd/miniforge3/envs/baf/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/home/evelyd/miniforge3/envs/baf/bin/gz', 'sdf', '-p', '/tmp/tmpbdv_is_d/tmpup45_c3y.xml']' returned non-zero exit status 255.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/evelyd/pi_learning_for_collaborative_carrying/scripts/retarget_onto_robot.py", line 49, in <module>
    js_model = js.model.JaxSimModel.build_from_model_description(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/evelyd/miniforge3/envs/baf/lib/python3.11/site-packages/jaxsim/api/model.py", line 120, in build_from_model_description
    intermediate_description = jaxsim.parsers.rod.build_model_description(
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/evelyd/miniforge3/envs/baf/lib/python3.11/site-packages/jaxsim/parsers/rod/parser.py", line 358, in build_model_description
    sdf_data = extract_model_data(
               ^^^^^^^^^^^^^^^^^^^
  File "/home/evelyd/miniforge3/envs/baf/lib/python3.11/site-packages/jaxsim/parsers/rod/parser.py", line 58, in extract_model_data
    sdf_element = rod.Sdf.load(sdf=model_description, is_urdf=is_urdf)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/evelyd/miniforge3/envs/baf/lib/python3.11/site-packages/rod/sdf/sdf.py", line 95, in load
    sdf_string = GazeboHelper.process_model_description_with_sdformat(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/evelyd/miniforge3/envs/baf/lib/python3.11/site-packages/rod/utils/gazebo.py", line 116, in process_model_description_with_sdformat
    raise RuntimeError(
RuntimeError: Failed to process the input with sdformat
```

It seems to maybe be an issue with rod based on the error content. My versions of rod and jaxsim are as follows:
```
rod                       0.3.3              pyhd8ed1ab_0    conda-forge
jaxsim                    0.4.2              pyhd8ed1ab_1    conda-forge
```

Is there some intermediate step I need to perform here, or something I should change in the urdf file?

**Comment by flferretti** [comment]
Hi @evelyd! I wasn't able to reproduce your error with the package versions that you mentioned. Could you please ensure that the argument passed to JaxSim is a `pathlib.Path`?

I report here what worked for me:

```python
from pathlib import Path
urdf_path = Path(
    "/home/flferretti/human-gazebo/humanSubjectWithMeshes/humanSubjectWithMesh.urdf"
)

# Test 1: Try to load the URDF using ROD
from rod import Sdf
_= Sdf.load(urdf_path)

# Test 2: Loading using JaxSim
import jaxsim.api as js
_= js.model.JaxSimModel.build_from_model_description(model_description=urdf_path)
```

**Comment by evelyd** [comment]
Thanks @flferretti! It turns out the error was caused simply by the path being wrong.

This error seems to be thrown because of the empty sdf file which contains only `<sdf version='1.4'/>`.

I'll close this issue then.

**Comment by flferretti** [comment]
> Not extremely problematic, but we may think of having a more clear if a file does not exists either in rod or jaxsim.

Done in https://github.com/ami-iit/rod/pull/50
