### ISSUE TITLE
ModuleNotFoundError: No module named 'rod.element'

### ISSUE THREAD

**Issue by stephane-caron** [ami-iit/rod#5]
Just installed rod from the README instruction:

```
pip install git+https://github.com/ami-iit/rod
```

Trying to import it afterwards:

```python
Python 3.8.10 (default, Jun 22 2022, 20:18:18) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import rod
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "~/.local/lib/python3.8/site-packages/rod/__init__.py", line 1, in <module>
    from .collision import Collision
  File "~/.local/lib/python3.8/site-packages/rod/collision.py", line 6, in <module>
    from .common import Pose
  File "~/.local/lib/python3.8/site-packages/rod/common.py", line 6, in <module>
    from .element import Element
ModuleNotFoundError: No module named 'rod.element'
```

**Comment by diegoferigo** [comment]
Hi @stephane-caron, thanks for the feedback. My bad, fixed in ca82e0aea0c426ddc2163b01b1d823aa99774054. Let me know if it works now, the library is still very young :)

**Comment by stephane-caron** [comment]
No worries :smiley: I reinstalled and it works now :ok_hand: Thanks for the quick fix!
